In [1]:
import numpy as np

In [2]:
1 / ( 1 + np.exp(-1))

0.36787944117144233

In [3]:
x = np.array([1, 2])

In [4]:
np.exp(1)

2.718281828459045

In [5]:
np.exp(x)

array([2.71828183, 7.3890561 ])

In [6]:
from utils.utils import softmax

In [11]:
softmax(np.array([[1, 2, 3], [2, 5, 8]]))

array([[0.09003057, 0.24472847, 0.66524096],
       [0.00235563, 0.04731416, 0.95033021]])

In [27]:
Uo = np.random.rand(3, 1)
U = np.random.rand(10, 3)

In [33]:
(Uo.T*U).sum(axis=1)

array([0.90509906, 1.03302226, 0.45047863, 0.75259038, 1.61179809,
       1.00382657, 0.84013403, 0.37498871, 0.67039022, 0.45008458])

In [32]:
Uo.T*U[0])

array([[0.80434808, 0.01889401, 0.08185696]])